### ISSUE TITLE
[FEATURE] add a way to get header data filled again into items

### ISSUE THREAD

**Issue by MahmoudMabrok** [Mohamad-Khalid/Resume-Creator#1]
add ability when to update header it get values from current fields back to input 
this allow fast updated in one time 

as example have header with name and email 
then want to update both in one time so when click header it will pre-fill inputs

**Comment by Mohamad-Khalid** [comment]
Issues solved.

**Comment by Mohamad-Khalid** [comment]
Solved

**Comment by MahmoudMabrok** [comment]
Try to solve issues with Pull Request and attach it to issue
